name: CI Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'   # Versión mínima requerida por Angular
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./   # raíz del repo frontend

      - name: Run tests
        run: npm test -- --watch=false --browsers=ChromeHeadless
        working-directory: ./   # raíz del repo frontend

      - name: Build project
        run: npm run build --if-present
        working-directory: ./   # raíz del repo frontend
