name: CI Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'   # versión Angular

      - name: Install dependencies
        run: npm install
        working-directory: ./   # raíz del repo frontend

      - name: Run tests
        run: npm test -- --watch=false --browsers=ChromeHeadless
        working-directory: ./   # raíz del repo frontend

      - name: Build project
        run: npm run build --if-present
        working-directory: ./   # raíz del repo frontend
